import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Menu } from "./components/menu";

// Load Inter font with specific weights
const inter = Inter({
  subsets: ["latin"], // Optional, only include Latin subset
  weight: ["100", "300", "400", "500", "700", "900"], // Provide weights as an array
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const interClassName = inter.className; // Garante consistência

  return (
    <html lang="en">
      <body
        className={`${interClassName}  text-green-950 bg-white antialiased flex flex-col w-full min-h-screen  items-center scroll-smooth`}
      >
        <Menu />
        {children}
      </body>
    </html>
  );
}
